import turtle
import tkinter

tkinter =tkinter.Tk
# mike=turtle.Pen()
# mike.color(0,0,1)
# mike.forward(90)
# mike.up()
# mike.forward(20)
# mike.left(270)
# mike.down()
# mike.forward(90)
# mike.up()
# mike.forward(20)
# mike.left(270)
# mike.down()
# mike.forward(90)
# mike.up()
# mike.forward(20)
# mike.left(270)
# mike.down()
# mike.forward(90)
# mike.up()
# mike.forward(20)
# mike.left(270)
# mike.down()
# olga=turtle.Pen()
# olga.color(1,0,0)
# olga.forward(90)
# olga.up()
# olga.forward(90)
# olga.left(10)
# olga.forward(45)
# olga.left(180)
# olga.down()
# olga.forward(90)
#
# olga.reset()
# mike.reset()
# mike.color(1,0,1)
# mike.begin_fill()
# for x in range(1,9):
#     mike.forward(50)
#     mike.right(45)
#     mike.end_fill()
#
# gimp= turtle.Pen()
# gimp.begin_fill()
# gimp.color(1,0.5,0)
# gimp.forward(50)
# gimp.left(120)
# gimp.forward(50)
# gimp.left(120)
# gimp.forward(50)
# gimp.reset()
# mike.reset()
#
# for x in range(1,90):
#     gimp.color(1,0.5,0)
#     gimp.begin_fill()
#     gimp.forward(56)
#     gimp.left(125)
#     gimp.forward(53)
#     gimp.left(90)
#     gimp.end_fill()
#
# for x in range(1,2):
#      mike.color(0,0,1)
#      mike.begin_fill()
#      mike.color(0, 0, 1)
#      mike.forward(90)
#      mike.up()
#      mike.forward(20)
#      mike.left(270)
#      mike.down()
#      mike.forward(90)
#      mike.up()
#      mike.forward(20)
#      mike.left(270)
#      mike.down()
#      mike.forward(90)
#      mike.up()
#      mike.forward(20)
#      mike.left(270)
#      mike.down()
#      mike.forward(90)
#      mike.up()
#      mike.forward(20)
#      mike.left(270)
#      mike.down()
#      olga = turtle.Pen()
#      olga.color(1, 0, 0)
#      olga.forward(90)
#      olga.up()
#      olga.forward(90)
#      olga.left(10)
#      olga.forward(45)
#      olga.left(180)
#      olga.down()
#      olga.forward(90)
#
#      olga.reset()
#      mike.reset()
#      mike.color(1, 0, 1)
#      mike.begin_fill()
#
# false=turtle.Pen()
# false.color(0,0,0)
# false.begin_fill()
# for x in range(1,5):
#     false.forward(111)
#     false.left(280)
# false.end_fill()
#
# true=turtle.Pen()
# true.color(1.1,1)
# true.begin_fill()
# true.forward(50)
# true.right(280)
# true.backward(50)
# true.clear()
#
# ter=turtle.Pen()
# ter.color(1,0,0)
# ter.begin_fill()
# ter.forward(100)
# ter.right(90)
# ter.backward(100)
# ter.left(280)
# ter.end_fill()
#
# i = turtle.Pen()
# i.color(1,0.7 ,1)
# i.begin_fill()
# i.forward(100)
# i.backward(100)
# i.circle(10)
# i.left(180)
# i.circle(1)
# i.left(180)
# i.backward(100)
# i.reset()

eqw=turtle.Pen()
eqw.color(False)
for x in range(1,5):
    eqw.forward(100)
    eqw.left(90)