fred=('''i'm Make says"i can swim and fly!"''')
v =('i have 9999 grn!')
m=(' And i will buy a robot!')
r =('i know a Python!')
e = ('happy easter!')
ere =('1qaz2wsx3edc4rfv5tgb6yhn7ujm8ik,9ol.0p;/-["=]\"')
qaz=('lljljljljljljljljljljl')
peouple =('know')
uy=("i don't  says false.")
alal=(".c.c..c.c")
ugftr=('78bjkmnm]-')
print(fred)
print(v)
print(m)
print(r)
print(e)
print(ere)
print(qaz)
print(peouple)
print(uy)
print(alal)
print(ugftr)